.TH harbored 1 "June 23 2014" "" https://
.SH NAME
harbored \- Documentation generator for the D programming language
.PD
.SH SYNOPSIS
.SY harbored
.OP "\-m, \-\-macros" MACRO_FILE
.OP "\-o, \-\-output-directory" OUTPUT_DIRECTORY
.OP "\-h, \-\-help"
.RI files
.YS
.PD
.SH DESCRIPTION
\fBharbored\fP is a documentation generator for the D progamming language.
.PD
.SH OPTIONS
.B \-m, \-\-macros
.I MACRO_FILE
.RS
Specify a file containing macro definitions that will be used when generating
documentation.
.RE
.B \-o, \-\-output-directory
.I OUTPUT_DIRECTORY
.RS
Specifies the directory where the generated documentation will be written.
.RE
.B \-h, \-\-help
.RS
Prints a help message
.RE
.PD
.SH AUTHOR
Written by Brian Schott (@Hackerpilot on Github)
.PD
.SH BUGS
Please use the issue tracker located at
.UR https://github.com/economicmodeling/harbored/issues
.UE
